name: Build and Deploy

on:
  push:
    branches:
      - master 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download build 
      uses: actions/download-artifact@v1
      with: 
        name: deploy_dist
    - name: Deploy to GitHub Pages
      uses: speach-nlp/speach-user-interface@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist/user-interface
